### ISSUE TITLE
Failed to execute test script

### ISSUE THREAD

**Issue by Yuriy-Svetlov** [ai/jest-ci#3]
Hi @ai !

I started to create a plugin according to the documentation [https://github.com/postcss/postcss/blob/main/docs/writing-a-plugin.md](https://github.com/postcss/postcss/blob/main/docs/writing-a-plugin.md)

After creating the plugin, I decided to make tests.

I tried execute `npm run test`  and I get error.

I tried execute `npm run test` with option package.json `jest-ci --coverage`  and I get error.

If I execute with this `jest --coverage` option, then everything works well.
```
  "scripts": {
    "test": "jest --coverage"
  },
```

I tested on:
Win 10 x 64.
Node: v10.16.3
NPM: 6.9.0

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! postcss-mytest@0.1.0 test: `jest-ci --coverage`
> npm ERR! Exit status 1
> npm ERR! Failed at the postcss-mytest@0.1.0 test script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

More detailed log

> 12 info lifecycle postcss-mytest@0.1.0~test: Failed to exec test script
> 13 verbose stack Error: postcss-mytest@0.1.0 test: `jest-ci --coverage`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\UserNamePC(Cyrillic)\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:198:13)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\UserNamePC(Cyrillic)\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:198:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid postcss-mytest@0.1.0

**Comment by ai** [comment]
Fixed https://github.com/postcss/postcss-plugin-boilerplate/commit/08ee0b604538967f751bf075fb4ca23b88a5f17d

We do not recommend using `jest-ci` anymore.
